# Alpine Packages and Repository

This directory contains the Alpine Linux package build system for multiple packages (e.g., `modbus2mqtt`, `lxc-manager`). It supports templated generation via INI files and generic build scripts.

## Structure

```
alpine/
├── package/           # Alpine package sources and templates
│   ├── apk-template/              # Generic template with .in files and APKBUILD.in
│   ├── common/node-build.sh       # Helper to rebuild native Node modules
│   ├── generate-ap.sh             # Generator: INI → package directory
│   ├── modbus2mqtt/               # Example generated/maintained package
│   └── lxc-manager/               # Example generated/maintained package
└── repo/             # Built packages (generated by package.sh)
    └── <arch>/       # Architecture-specific packages
        └── *.apk     # Built APK packages
```

## Generate and Build Packages

### Prerequisites

- Docker
- Environment variable:
  - `PACKAGER_PRIVKEY` - Private abuild key (public key is derived automatically)

### Generate from INI

Create an INI file (e.g., `alpine/package/modbus2mqtt.ini`):

```ini
pkgname=modbus2mqtt
pkgver=0.16.57
pkgrel=0
pkgdesc=Modbus to MQTT bridge
url=https://github.com/modbus2mqtt/server
license=MIT
depends="nodejs npm s6-overlay git openssh-server"
npmpackage=modbus2mqtt
app_dirs="/config /data /ssl"
app_dirs_owner="modbus2mqtt:dialout"
```

Generate the package directory:
```bash
cd alpine/package
./generate-ap.sh modbus2mqtt modbus2mqtt.ini
```

### Build APKs

```bash
# Build package (requires abuild setup and PACKAGER_PRIVKEY)
cd alpine/package/modbus2mqtt
abuild -r

# Built packages land in:
ls -la ../../repo/<arch>
```

## Use the Repository

Add the repository to your Alpine system:

```bash
# Copy the public key
sudo cp alpine/repo/<arch>/builder-*.rsa.pub /etc/apk/keys/

# Add repository to apk
echo "/path/to/alpine/repo/<arch>" | sudo tee -a /etc/apk/repositories

# Update and install
sudo apk update
sudo apk add <pkgname>
```

## Docker Image Build

Use the generic Docker build script which can optionally generate package dirs from INI:

```bash
# Build using existing repo APKs
./docker/build.sh 0.1.0 --tag modbus2mqtt

# Or generate package dirs from INI first
./docker/build.sh 0.1.0 --generate --tag modbus2mqtt
```

The Dockerfile expects signed APKs in `alpine/repo/<arch>/` and installs `PACKAGE_NAME-*.apk`.

## Notes

- `repo/` is generated during build and not committed to git.
- `apk-template/` contains the generic files used by `generate-ap.sh`.
- OpenSSH setup in `post-install` is optional and runs only if `sshd` is present.
