#!/usr/bin/env node
/**
 * Maintains json/shared/parameter-definitions.md.
 *
 * 1. Seeds missing sections from parameter-definitions.json descriptions.
 *    Idempotent: existing `## <id>` sections are preserved verbatim
 *    (the body / sub-sections are hand-edited afterwards).
 *
 * 2. Refreshes a "### Used by" sub-section at the bottom of every parameter
 *    section. Visible bullets list addons and applications only — that's
 *    the consumer-level information end users care about. Templates and
 *    frameworks that reference the parameter are recorded in an HTML
 *    comment block for traceability without cluttering the help panel.
 *    The whole block is delimited by `<!-- used-by:start -->` /
 *    `<!-- used-by:end -->` markers so it is safe to re-run.
 *
 * Run after 03-build-definitions.mjs so the registry is up-to-date.
 */

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, dirname, relative, basename } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(SCRIPT_DIR, "..", "..");
const JSON_ROOT = join(REPO_ROOT, "json");
const EXAMPLES_ROOT = join(REPO_ROOT, "examples");
const WALK_ROOTS = [JSON_ROOT, EXAMPLES_ROOT];
const DEFINITIONS_PATH = join(JSON_ROOT, "shared", "parameter-definitions.json");
const MD_PATH = join(JSON_ROOT, "shared", "parameter-definitions.md");
const SKIP_DIRS = new Set(["applications-backup"]);
const SKIP_FILES = new Set([
  "json/shared/parameter-definitions.json",
  "examples/storagecontext.json",
  "examples/refresh-history.json",
  "examples/enum-values-cache.json",
]);

const HEADER = `# Parameter Documentation

Canonical descriptions for the parameters defined in
\`parameter-definitions.json\`. Each \`## <id>\` section is the help text
shown in the installation UI (rendered as Markdown via the help-icon
expand panel).

The validator enforces *exactly one* description source per parameter:
a section here OR a JSON \`description\` field — not both, not neither.
Use this file for rich, multi-paragraph help; keep JSON \`description\`
for parameters where a single tooltip-line is enough.

The "### Used by" sub-section is auto-generated by
\`scripts/migration/06-seed-md.mjs\`. Visible bullets list addons and
applications only; templates and frameworks live in the HTML comment
block (visible in the source, hidden in rendered Markdown). Edit
anything outside the \`<!-- used-by:start -->\` / \`<!-- used-by:end -->\`
markers freely.

A "_registry-only_" Used-by line indicates that the parameter is
defined and referenced by some template, but that template is not
wired up from any addon / application's installation phases. This
is usually one of two things:

- **a runtime-only mechanism** — refresh templates (\`refresh/*.json\`)
  and test fixtures (\`test-python-shebang.json\`) are reached by their
  own runtime APIs, not by the install pipeline. Expected.
- **a missing JSON wiring (bug)** — the template is dead code from the
  installation perspective. See <https://github.com/proxvex/proxvex/issues/216>
  for the catalogue of known cases.

`;

const USED_BY_BEGIN = "<!-- used-by:start -->";
const USED_BY_END = "<!-- used-by:end -->";

async function* walkJson(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      yield* walkJson(full);
    } else if (entry.isFile() && entry.name.endsWith(".json")) {
      const rel = relative(REPO_ROOT, full);
      if (SKIP_FILES.has(rel)) continue;
      yield full;
    }
  }
}

/** Classify a json file path. */
function classifyFile(rel) {
  const addon = rel.match(/^json\/addons\/([^/]+)\.json$/);
  if (addon) return { kind: "addon", id: addon[1] };
  const app = rel.match(/^json\/applications\/([^/]+)\/application\.json$/);
  if (app) return { kind: "app", id: app[1] };
  const exApp = rel.match(/^examples\/applications\/([^/]+)\/application\.json$/);
  if (exApp) return { kind: "app", id: exApp[1] };
  const fw = rel.match(/^json\/frameworks\/([^/]+)\.json$/);
  if (fw) return { kind: "framework", id: fw[1] };
  if (
    rel.startsWith("json/shared/templates/") ||
    rel.match(/^json\/applications\/[^/]+\/templates\//) ||
    rel.match(/^examples\/applications\/[^/]+\/templates\//) ||
    rel.match(/^examples\/shared\/templates\//)
  ) {
    return { kind: "template", id: basename(rel) };
  }
  return { kind: "other", id: rel };
}

/** Visit every value reachable from a deployable's installation/* phases. */
function visitPhaseTree(node, fn) {
  if (Array.isArray(node)) {
    for (const item of node) {
      if (typeof item === "string") fn(item);
      else if (item && typeof item === "object") {
        if (typeof item.name === "string") fn(item.name);
        if (typeof item.template === "string") fn(item.template);
      }
    }
  } else if (node && typeof node === "object") {
    for (const v of Object.values(node)) visitPhaseTree(v, fn);
  }
}

/**
 * Build:
 *   - paramRefs: Map<paramId, Set<filePath>>
 *   - templateConsumers: Map<templateBasename, Set<consumerKey>>
 *     where consumerKey is "addon:X" | "app:X" | "framework:X" | "template:basename"
 *
 * `templateConsumers` is later closed over template→template edges so a
 * leaf template inherits the addon/app that pulls in its parent template.
 */
async function scanRepo() {
  const paramRefs = new Map();
  const fileToConsumer = new Map(); // filePath → consumerKey for addons/apps/frameworks
  const templateConsumers = new Map(); // templateBasename → Set<consumerKey>
  const addRef = (id, path) => {
    if (!paramRefs.has(id)) paramRefs.set(id, new Set());
    paramRefs.get(id).add(path);
  };
  const addConsumer = (template, consumerKey) => {
    if (!templateConsumers.has(template)) templateConsumers.set(template, new Set());
    templateConsumers.get(template).add(consumerKey);
  };

  for (const root of WALK_ROOTS) {
    let exists = true;
    try { await readdir(root); } catch { exists = false; }
    if (!exists) continue;
    for await (const file of walkJson(root)) {
      const rel = relative(REPO_ROOT, file);
      let parsed;
      try { parsed = JSON.parse(await readFile(file, "utf8")); } catch { continue; }
      const cls = classifyFile(rel);

      // Record parameter references.
      if (Array.isArray(parsed.parameters)) {
        for (const p of parsed.parameters) {
          const id = typeof p === "string" ? p : p?.id;
          if (typeof id === "string") addRef(id, rel);
        }
      }

      // Build consumer-key for this file.
      let consumerKey = null;
      if (cls.kind === "addon") consumerKey = `addon:${cls.id}`;
      else if (cls.kind === "app") consumerKey = `app:${cls.id}`;
      else if (cls.kind === "framework") consumerKey = `framework:${cls.id}`;
      else if (cls.kind === "template") consumerKey = `template:${cls.id}`;

      if (cls.kind !== "other") {
        fileToConsumer.set(rel, consumerKey);
      }

      if (consumerKey) {
        // Phase trees on deployables.
        for (const phase of ["installation", "reconfigure", "upgrade", "check", "disable"]) {
          if (parsed[phase]) visitPhaseTree(parsed[phase], (t) => addConsumer(t, consumerKey));
        }
        // commands[].template — templates including other templates.
        if (Array.isArray(parsed.commands)) {
          for (const cmd of parsed.commands) {
            if (cmd && typeof cmd.template === "string") {
              addConsumer(cmd.template, consumerKey);
            }
          }
        }
      }
    }
  }

  // Transitive closure: if templateA's consumers include templateB, then
  // templateA also inherits templateB's consumers (recursively), but we
  // strip the "template:..." entries from the final output so leaves end
  // up with only addon/app/framework consumers.
  let changed = true;
  let guard = 10;
  while (changed && guard-- > 0) {
    changed = false;
    for (const [tpl, set] of templateConsumers) {
      for (const c of [...set]) {
        if (!c.startsWith("template:")) continue;
        const parentTpl = c.slice("template:".length);
        const parentSet = templateConsumers.get(parentTpl);
        if (!parentSet) continue;
        for (const x of parentSet) {
          if (!set.has(x)) {
            set.add(x);
            changed = true;
          }
        }
      }
    }
  }

  return { paramRefs, fileToConsumer, templateConsumers };
}

/** Render the "### Used by" block for one parameter. */
function renderUsedBy(id, files, fileToConsumer, templateConsumers) {
  const visible = new Set(); // displayable strings, addons + apps
  const templateLines = []; // for hidden comment

  for (const file of [...files].sort()) {
    const cls = classifyFile(file);
    if (cls.kind === "addon") {
      visible.add(`${cls.id}`);
    } else if (cls.kind === "app") {
      visible.add(cls.id);
    } else if (cls.kind === "framework") {
      // Frameworks are metadata-only — keep them in the comment, not visible.
      templateLines.push(`- ${file} (framework metadata)`);
    } else if (cls.kind === "template") {
      const cons = templateConsumers.get(cls.id);
      const trail = [];
      if (cons) {
        for (const c of cons) {
          if (c.startsWith("addon:")) {
            visible.add(c.slice("addon:".length));
            trail.push(c.slice("addon:".length));
          } else if (c.startsWith("app:")) {
            visible.add(c.slice("app:".length));
            trail.push(c.slice("app:".length));
          } else if (c.startsWith("framework:")) {
            trail.push(`framework:${c.slice("framework:".length)}`);
          }
        }
      }
      const trailText = trail.length > 0 ? ` (via ${trail.sort().join(", ")})` : "";
      templateLines.push(`- ${file}${trailText}`);
    } else {
      templateLines.push(`- ${file}`);
    }
  }

  const sortedVisible = [...visible].sort();
  const visiblePart = sortedVisible.length > 0
    ? sortedVisible.map((s) => `- ${s}`).join("\n")
    : "_(registry-only — not referenced by any application or addon)_";

  let hidden = "";
  if (templateLines.length > 0) {
    hidden = `\n<!--\nTemplates / frameworks referencing this parameter:\n${templateLines.join("\n")}\n-->`;
  }

  return `### Used by\n\n${USED_BY_BEGIN}\n${visiblePart}\n${USED_BY_END}${hidden}\n`;
}

/** Split the existing MD into header + per-id sections. */
function splitSections(md) {
  if (!md) return { header: HEADER, sections: new Map() };
  const lines = md.split(/\r?\n/);
  let i = 0;
  for (; i < lines.length; i++) if (/^##\s+[A-Za-z_]/.test(lines[i])) break;
  const header = lines.slice(0, i).join("\n").replace(/\s+$/, "") + "\n\n";
  const sections = new Map();
  let currentId = null;
  let buf = [];
  const flush = () => {
    if (currentId !== null) {
      sections.set(currentId, buf.join("\n").replace(/\s+$/, "") + "\n");
    }
  };
  for (; i < lines.length; i++) {
    const m = lines[i].match(/^##\s+([A-Za-z_][A-Za-z0-9_.-]*)\s*$/);
    if (m) {
      flush();
      currentId = m[1];
      buf = [lines[i]];
    } else {
      buf.push(lines[i]);
    }
  }
  flush();
  return { header, sections };
}

/**
 * Replace the existing "### Used by" block (and any HTML comment that
 * directly follows it) with the freshly-built one. Preserves everything
 * above and any non-used-by content below.
 */
function updateUsedBy(sectionText, freshBlock) {
  // Strip any "### Used by" heading and the start..end markers, plus any
  // immediately-following HTML comment that holds the template list.
  const re = new RegExp(
    `\\n+\\s*###\\s+Used by[\\s\\S]*?${USED_BY_END}\\s*(\\n+<!--[\\s\\S]*?-->\\s*)?`,
    "m",
  );
  let body = sectionText.replace(re, "");
  body = body.replace(/\s+$/, "");
  return `${body}\n\n${freshBlock}`;
}

function buildSection(id, def, freshBlock) {
  const desc = (def?.description ?? "").trim();
  const body = desc !== "" ? desc : `_(no description yet — please add one)_`;
  return `## ${id}\n\n${body}\n\n${freshBlock}`;
}

async function main() {
  const definitions = JSON.parse(await readFile(DEFINITIONS_PATH, "utf8"));
  const params = definitions.parameters ?? {};
  const ids = Object.keys(params).sort((a, b) => a.localeCompare(b));

  const { paramRefs, fileToConsumer, templateConsumers } = await scanRepo();

  let existing;
  try { existing = await readFile(MD_PATH, "utf8"); } catch { existing = null; }
  const { header, sections } = splitSections(existing);

  let added = 0;
  let refreshed = 0;
  for (const id of ids) {
    const files = paramRefs.get(id) ?? new Set();
    const block = renderUsedBy(id, files, fileToConsumer, templateConsumers);
    if (sections.has(id)) {
      const updated = updateUsedBy(sections.get(id), block);
      if (updated !== sections.get(id)) refreshed++;
      sections.set(id, updated);
    } else {
      sections.set(id, buildSection(id, params[id], block));
      added++;
    }
  }

  const orphans = [...sections.keys()].filter((id) => !(id in params));
  if (orphans.length > 0) {
    console.log(`WARNING: ${orphans.length} orphan section(s): ${orphans.join(", ")}`);
  }

  const ordered = ids
    .map((id) => sections.get(id))
    .concat(orphans.map((id) => sections.get(id)));
  // Always emit the canonical HEADER so updates to it (e.g. doc URLs)
  // propagate when the script is re-run. Anything between the file's
  // start and the first `## <id>` heading is regenerated.
  const md =
    HEADER +
    ordered.map((s) => s.replace(/\n+$/, "")).join("\n\n") +
    "\n";
  await writeFile(MD_PATH, md);

  console.log(`Sections in MD: ${ordered.length}`);
  console.log(`  added:        ${added}`);
  console.log(`  refreshed:    ${refreshed} (used-by block updated)`);
  if (orphans.length > 0) console.log(`  orphans:      ${orphans.length}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
